export const companyName = "Panto";

export const categoriesName = [
  {
    id: 0,
    category: "chair",
  },
  {
    id: 1,
    category: "bed",
  },
  {
    id: 2,
    category: "sofa",
  },
  {
    id: 3,
    category: "lamp",
  },
];

export const products = [
  {
    title: "Chair",
    image: "/src/assets/images/products/product_1.png",
    description: "Sakarias armchair",
    price: 392,
    rating: 4.5,
    category: "chair",
  },
  {
    title: "Chair",
    image: "/src/assets/images/products/product_2.png",
    description: "baltsar chair",
    price: 299,
    rating: 5,
    category: "chair",
  },
  {
    title: "Chair",
    image: "/src/assets/images/products/product_3.png",
    description: "Anjoy chair",
    price: 500,
    rating: 3.5,
    category: "chair",
  },
  {
    title: "Chair",
    image: "/src/assets/images/products/product_4.png",
    description: "Nyantuy  chair",
    price: 600,
    rating: 3,
    category: "chair",
  },
  {
    title: "Chair",
    image: "/src/assets/images/products/product_1.png",
    description: "Nyantuy  chair",
    price: 600,
    rating: 3,
    category: "chair",
  },
  {
    title: "bed",
    image: "/src/assets/images/products/product_4.png",
    description: "Sakarias armchair",
    price: 392,
    rating: 4.5,
    category: "bed",
  },
  {
    title: "bed",
    image: "/src/assets/images/products/product_3.png",
    description: "baltsar chair",
    price: 299,
    rating: 5,
    category: "bed",
  },
  {
    title: "bed",
    image: "/src/assets/images/products/product_2.png",
    description: "Anjoy  chair",
    price: 500,
    rating: 3.5,
    category: "bed",
  },
  {
    title: "bed",
    image: "/src/assets/images/products/product_1.png",
    description: "Anjoy  chair",
    price: 500,
    rating: 3.5,
    category: "bed",
  },
  {
    title: "bed",
    image: "/src/assets/images/products/product_1.png",
    description: "Nyantuy  chair",
    price: 600,
    rating: 3,
    category: "bed",
  },
  {
    title: "sofa",
    image: "/src/assets/images/products/product_1.png",
    description: "Sakarias armchair",
    price: 392,
    rating: 4.5,
    category: "sofa",
  },
  {
    title: "sofa",
    image: "/src/assets/images/products/product_2.png",
    description: "baltsar chair",
    price: 299,
    rating: 5,
    category: "sofa",
  },
  {
    title: "sofa",
    image: "/src/assets/images/products/product_3.png",
    description: "Anjoy  chair",
    price: 500,
    rating: 3.5,
    category: "sofa",
  },
  {
    title: "sofa",
    image: "/src/assets/images/products/product_4.png",
    description: "Nyantuy  chair",
    price: 600,
    rating: 3,
    category: "sofa",
  },
  {
    title: "sofa",
    image: "/src/assets/images/products/product_1.png",
    description: "Nyantuy  chair",
    price: 600,
    rating: 3,
    category: "sofa",
  },
  {
    title: "lamp",
    image: "/src/assets/images/products/product_4.png",
    description: "Nyantuy  chair",
    price: 600,
    rating: 3,
    category: "lamp",
  },
  {
    title: "lamp",
    image: "/src/assets/images/products/product_3.png",
    description: "Sakarias armchair",
    price: 392,
    rating: 4.5,
    category: "lamp",
  },
  {
    title: "lamp",
    image: "/src/assets/images/products/product_2.png",
    description: "baltsar chair",
    price: 299,
    rating: 5,
    category: "lamp",
  },
  {
    title: "lamp",
    image: "/src/assets/images/products/product_1.png",
    description: "Anjoy  chair",
    price: 500,
    rating: 3.5,
    category: "lamp",
  },
  {
    title: "lamp",
    image: "/src/assets/images/products/product_4.png",
    description: "Anjoy  chair",
    price: 500,
    rating: 3.5,
    category: "lamp",
  },
];

export const breakpoints = {
  0: {
    slidesPerView: 1,
    spaceBetween: 10,
  },
  768: {
    slidesPerView: 2,
    spaceBetween: 20,
  },
  1024: {
    slidesPerView: 3,
    spaceBetween: 40,
  },
  1440: {
    slidesPerView: 4,
    spaceBetween: 60,
  },
};
